#!/bin/bash

/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj1/40Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj1/50Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj1/60Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj2/40Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj2/50Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj2/60Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj4/40Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj4/50Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj4/60Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj8/40Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj8/50Demands/onlineParameters.txt;
/mnt/c/FlexOptim/RSA/src/exec /mnt/c/FlexOptim/RSA/Parameters/SEA/EdgeNode/NSF/Obj8/60Demands/onlineParameters.txt;